name: Java CI

on: [push, pull_request_target]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-jdk17-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - uses: mate-academy/auto-approve-action@v2
        if: ${{ github.event.pull_request && success() }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: mate-academy/auto-reject-action@v2
        if: ${{ github.event.pull_request && failure() }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
